name: Test Action

on:
  push:
    branches:
      - main  # Change this if you want to trigger the action on another branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f3001109@ds.study.iitm.ac.in
        run: echo "Hello, world!"
